# Generated by Django 5.2.14 on 2026-05-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='mood',
            field=models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('productive', 'Productive')], default='happy', max_length=20),
        ),
    ]
